services:
  spring-boot-app:
    container_name: spring-boot-app-container
    image: spring-boot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres-db-container
    image: postgres:latest
    environment:
      POSTGRES_USER: #your_username
      POSTGRES_PASSWORD: #your_password
      POSTGRES_DB: e_commerce_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: